[feat|fix] : SDE frontend : Hotfix 3.2 with pcf - rel:2.3.0
eclipse-tractusx/managed-simple-data-exchanger-frontend pull request #38
Opened 2023-11-21 13:01 UTC by sachinargade123

## Description
### Fixed

- Code optimisation for download file from server, Generic error handling, UI improvement .
- trivy workflow updated.
- version bump for chart release.
- PCF documentation update

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-11-22 03:20 UTC, ajithsimons commented
@almadigabor  Could you please help us create dependency review tickets for the below libraries?
npm/npmjs/@babel/code-frame/7.23.4
npm/npmjs/@babel/helper-string-parser/7.23.4
npm/npmjs/@babel/highlight/7.23.4

Thanks!

2023-11-22 07:19 UTC, carslen commented
Done:

```
[main] INFO Querying Eclipse Foundation for license data for 500 items.
[main] INFO Found 145 items.
[main] INFO Querying Eclipse Foundation for license data for 500 items.
[main] INFO Found 94 items.
[main] INFO Querying Eclipse Foundation for license data for 290 items.
[main] INFO Found 51 items.
[main] INFO Querying ClearlyDefined for license data for 500 items.
[main] INFO Found 500 items.
[main] INFO Querying ClearlyDefined for license data for 500 items.
[main] INFO Found 500 items.
[main] INFO License information could not be automatically verified for the following content:
[main] INFO
[main] INFO npm/npmjs/@babel/code-frame/7.23.4
[main] INFO npm/npmjs/@babel/helper-string-parser/7.23.4
[main] INFO npm/npmjs/@babel/highlight/7.23.4
[main] INFO
[main] INFO This content is either not correctly mapped by the system, or requires review.
[main] INFO A review is required for npm/npmjs/@babel/highlight/7.23.4.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11658 .
[main] INFO A review is required for npm/npmjs/@babel/code-frame/7.23.4.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11659 .
[main] INFO A review is required for npm/npmjs/@babel/helper-string-parser/7.23.4.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11660 .
```

Tickets created:
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11658
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11659
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11660

2023-11-22 09:32 UTC, carslen requested changes

2023-11-22 09:32 UTC, carslen commented on DEPENDENCIES
> +npm/npmjs/@babel/code-frame/7.23.4, , restricted, clearlydefined
Please update `DEPENDENCIES` file after successfull IP-Check for restricted 3rd party libs.

2023-11-22 09:40 UTC, ajithsimons commented
@carslen  thanks for the quick support! Dependencies file has been updated. Please verify!

2023-11-23 09:27 UTC, MehranRoshandel commented
@carslen, can you please help us to merge this PR by today?

2023-11-23 09:38 UTC, adityagajbhiye9 commented
Updated.
#41  Legal documents updated for docker image.

2023-11-23 11:18 UTC, adityagajbhiye9 commented
fixed
#41 Updated Docker file for legal information

2023-11-24 10:28 UTC, hzierer commented
@carslen Dockerfile LGTM now

2023-11-27 10:57 UTC, FaGru3n commented
Hi all,

in my opinion this is really hard to verfiy and IMHO i would reject this PR.

This looks for me to one PR to fix all problems...  👎🏼 not a good practice in my perspective.

Reason: 
- Hard to review
- No transparency on what change fixed which issue  without dedicated commit messages, etc.
- Hard/impossible to create a proper changelog

The Best practices we nomally use 1 problem like docs / 1 pr / dedicated commit messages why to change and what to improve.

if i read the description correctly that would be at least 6 PR´s like:

1. Code optimisation for download file from server
2. Generic error handling
3. UI improvement
4. trivy workflow updated
5. version bump for chart release
6. PCF documentation update

Only guessing is it possible for you @sachinargade123 to split all your changes in separate PR´s or generating new ones? This is also the reason why we as a system team generate multible issues for each TRG seaction.

2023-11-28 09:49 UTC, sachinargade123 commented
We are closing this PR. We will create new PR's.

2023-11-28 09:49 UTC, closed without merging