feat!(policies): Policies from policy hub
eclipse-tractusx/managed-simple-data-exchanger-frontend pull request #79
Opened 2024-03-19 11:42 UTC by ajithsimons

## Description

- Policies will be dynamically fetched from policy hub based on the selected/available use cases in SDE.
- Frontend components will be dynamically rendered based on the policy type.
- Re-usable loading handlers for api calls

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-20 11:16 UTC, sachinargade123 approved these changes
LGTM

2024-03-20 11:19 UTC, sachinargade123 requested changes
@ajithsimons if we don't want to release this list of changes, Can you create un-realese section in change log and mentioned all the changes?

2024-03-21 04:07 UTC, adityagajbhiye9 requested changes

2024-03-21 04:09 UTC, adityagajbhiye9 approved these changes
LGTM

2024-03-21 07:56 UTC, almadigabor approved these changes

2024-03-21 07:56 UTC, merged